const userTypes = {
	USER_LOGGEDIN: 'USER_LOGGEDIN',
	USER_LOGGEDOUT: 'USER_LOGGEDOUT',
	USER_PROFILE_UPDATE: 'USER_PROFILE_UPDATE',
	ADD_FAVORITE_POST: 'ADD_FAVORITE_POST'
};

export default userTypes;
