const userTypes = {
	USER_LOGGEDIN: 'USER_LOGGEDIN',
	USER_LOGGEDOUT: 'USER_LOGGEDOUT',
	USER_PROFILE_UPDATE: 'USER_PROFILE_UPDATE',
	ADD_FAVORITE_POST: 'ADD_FAVORITE_POST',
	USER_STATUS_TOGGLE: 'USER_STATUS_TOGGLE',
	DELETE_USER: 'DELETE_USER'
};

export default userTypes;
